import Foundation

/// Build token for development mode device registration
///
/// ⚠️ THIS FILE IS AUTO-GENERATED DURING RELEASES
/// ⚠️ DO NOT MANUALLY EDIT THIS FILE
///
/// Generated: 2025-10-31 08:42:18 UTC
/// Release: Auto-generated by scripts/release_ios_sdk.sh
///
/// Security Model:
/// - This file is in .gitignore (not committed to main branch)
/// - Real tokens are ONLY in release tags (for SPM distribution)
/// - Token is used ONLY when SDK is in .development mode
/// - Backend validates token via POST /api/v1/devices/register/dev
///
/// Token Properties:
/// - Format: bt_<uuid>_<timestamp>
/// - Rotatable: Each release gets a new token
/// - Revocable: Backend can mark token as inactive
/// - Rate-limited: Backend enforces 100 req/min per device
enum BuildToken {
    /// Development mode build token
    /// Generated at: 2025-10-31 08:42:18 UTC
    static let token = "bt_dafb8224-e0f5-43f0-a1b3-9c9a8b458a3e_1761900128"
}
